name: Electron Build and Publish

on:
  push:
    tags:
      - 'v*.*.*'  # Publish on tag push (e.g., v1.0.0)
    branches:
      - main  # Optional: Publish on main branch push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Wine
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y wine wine32 wine64

      - name: Clear Electron Builder Cache
        run: rm -rf ~/.cache/electron-builder

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build and Publish Electron app
        run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: electron-app
          path: dist
