name: Electron Build and Publish

on:
  push:
    tags:
      - 'v*.*.*'  # Publish on tag push (e.g., v1.0.0)
    branches:
      - main  # Optional: Publish on main branch push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install
      - run: npm run build --publish always
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - uses: actions/upload-artifact@v2
        with:
          name: windows-installer
          path: dist/*.exe
        if: success()